//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkTeam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eventos
    {
        public int Hora { get; set; }
        public string Fecha { get; set; }
        public string Evento { get; set; }
    }
}
