//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkTeam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materia
    {
        public int codigo { get; set; }
        public string Nombre { get; set; }
        public int AlumnoId { get; set; }
    
        public virtual Alumno Alumno { get; set; }
    }
}
